openapi: 3.0.0
info:
  title: Closure test
  version: "1.0.0"
servers:
  - url: https://example.com
security:
  - bearerAuth: []
paths:
  /example:
    get:
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
